services:
    backend:
        build:
            context: ./backend
        container_name: loctrack-backend
        ports:
            - "5000:5000"
        volumes:
            - ./data:/app/data
        environment:
            - FLASK_APP=app
            - FLASK_RUN_HOST=0.0.0.0

    test:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: pytest
        volumes:
            - ./data:/app/data
        environment:
            - FLASK_APP=app
            - PYTHONPATH=/app

    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        restart: unless-stopped
